### ISSUE TITLE
Possibility to change NPC peds

### ISSUE THREAD

**Issue by Geckomacabre** [BirddMann/npc_police#1]
I have a NY server and State Trooper Ped models for the s_m_y_hwaycop_01 could it be possible to switch which peds are patrolling around?

**Comment by BirddMann** [comment]
I believe this can be done by streaming dispatch.meta, but not with my current file set.  I haven't found a way to stream dispatch.meta yet but I am looking, there are some other things I'd like to modify in that file too....
